MA-22278-1 update privapp permission to solve boot up issues
when SearchLauncherQuickStep is removed from the gms package, issues are
encountered when boot up the system. Failure logs like below can be
found. Update the privapp permission based on the log.

java.lang.IllegalStateException: Signature|privileged permissions not in
privapp-permissions allowlist: {com.google.android.googlequicksearchbox
(/product/priv-app/Velvet): android.permission.RECEIVE_SANDBOX_TRIGGER_AUDIO}

Signed-off-by: faqiang.zhu <faqiang.zhu@nxp.com>
Change-Id: I4935f85fea1ca5ec9cd98990f71c79b903cb463e
Reviewed-on: http://androidsource.nxp.com/project/24411
Reviewed-by: Elven Wang <elven.wang@nxp.com>