MA-21817-1 Revert "MA-21817 Build some Demo APKs into mx95"
This reverts commit 12eb5014be6f420081e4388f2152128c3d56b01d.

Remove these prebuild demo apks on 95 to fix following
build errors with GMS package:
  RuntimeError: sum of sizes of ['system', 'system_dlkm', 'system_ext', 'vendor', 'vendor_dlkm', 'product']
  is greater than BOARD_SUPER_PARTITION_SIZE:
  643051520+7454720+89038848+2688425984+1568768+1605795840 == 5035335680 > 4294967296 == 4294967296

Change-Id: I76d4e37fd761485c924c16989f2ffad39a0e5f06
Reviewed-on: http://androidsource.nxp.com/project/23809
Reviewed-by: Jessie Hao <juan.hao@nxp.com>
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>